### ISSUE TITLE
invalid ELF header

### ISSUE THREAD

**Issue by konsumer** [tobilg/duckdb-nodejs-layer#3]
I am probably doing something wrong, but I keep getting ` /var/task/node_modules/duckdb/lib/binding/duckdb.node: invalid ELF header` in my AWS logs.

I am on mac M1, and I have this in my serverless.yml:
```yaml
service: REDACTED

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1' # Enable HTTP keep-alive connections for the AWS SDK
    LOG_LEVEL: 'debug'

functions:
  search:
    handler: src/handlers/search.search
    memorySize: 10240
    timeout: 30
    events:
      - http:
          path: '/'
          method: post
          cors: true
          # private: true
    layers:
      - 'arn:aws:lambda:us-west-2:041475135427:layer:duckdb-nodejs-x86:3'
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource: 'arn:aws:s3:::REDACTED/*'
      - Effect: Allow
        Action:
          - s3:ListBucket
        Resource: 'arn:aws:s3:::REDACTED'

package:
  individually: true

plugins:
  - serverless-iam-roles-per-function
  - serverless-offline
  - serverless-esbuild

custom:
  esbuild:
    external:
      - duckdb

```

It runs ok locally (with `serverless-offline`.) Does this not work with `serverless-esbuild`? I am just guessing, but it seems like it might not be using the layer correctly, like it's maybe trying to use my local M1 native `duckdb.node`?

**Comment by konsumer** [comment]
Maybe I am using this wrong? I am trying to just use node duckdb normally, in my code:

```js
import { Database } from 'duckdb'
import { promisify } from 'util'

const db = new Database(':memory:')
const query = promisify(db.all.bind(db))

export const search = async (event, context) => {
  // do query here
}
```

**Comment by tobilg** [comment]
Did you have a look at https://github.com/tobilg/serverless-duckdb?

i assume that your esbuild config doesn‘t exclude the locally installed DuckDB version, which will be ARM. Your Lambda function is x86_64 thought. 

See https://www.serverless.com/plugins/serverless-esbuild and look for „external“.

**Comment by tobilg** [comment]
Ah, I just saw that you have your plugins in the incorrect order, esbuild apparently needs to be before serverless-offline:

> Add the plugins to your serverless.yml file and make sure that serverless-esbuild precedes serverless-offline as the order is important:

**Comment by konsumer** [comment]
> Ah, I just saw that you have your plugins in the incorrect order, esbuild apparently needs to be before serverless-offline:

All the other functions (I define a few others) work fine in that order, but I switched them, and it has same issue. It also works fine locally (offline) just not remotely.

> i assume that your esbuild config doesn‘t exclude the locally installed DuckDB version, which will be ARM. Your Lambda function is x86_64 thought.

I also assume this, but `external` does not seem to work.

> See https://www.serverless.com/plugins/serverless-esbuild and look for „external“.

Yep, I  have this:

```yml
custom:
  esbuild:
    external:
      - duckdb
```

I deployed your demo, and it works like a charm. I was also thinking I could use that invoked from another lambda, but I could not seem to get he permissions on calling lambda working using `serverless-iam-roles-per-function`:

```yml
    iamRoleStatements:
      - Effect: Allow
        Action:
          - lambda:InvokeFunction
          - lambda:InvokeAsync
        Resource: 'arn:aws:lambda:::function:duckdb-prd-query'
```

Another idea is to just switch to webpack, like you use, in demo. I like esbuild's simpler config & faster build better, but I can't seem to get it to work.

**Comment by tobilg** [comment]
Regarding the IAM permissions, you‘ll need to add this to the calling function, not the DuckDB Lambda itself (if you didn‘t already)… Your ARN looks incomplete, it’s missing the Region for example

**Comment by konsumer** [comment]
> Regarding the IAM permissions, you‘ll need to add this to the calling function, not the DuckDB Lambda itself 
Yep, that is what I did.

> Your ARN looks incomplete, it’s missing the Region for example
Hmm, I may have misunderstood AWS docs, but the `:::` are placeholders. This works for S3, at least. I tried with the full ARN, and got same `AccessDenied` in logs.

**Comment by tobilg** [comment]
The ARN structure isn‘t the same for every service, here‘s the docs:

https://docs.aws.amazon.com/lambda/latest/dg/lambda-api-permissions-ref.html

A function needs to have a region in its ARN

**Comment by tobilg** [comment]
Regarding esbuild settings, I have a sample project that uses the following:

```yaml
# esbuild settings
esbuild:
  bundle: true
  minify: false
  exclude:
    - duckdb
``` 

This works for me at least. Please also try to temporarily disable `serverless-offline`, the redeploy. Does this change something?

**Comment by konsumer** [comment]
> The ARN structure isn‘t the same for every service, here‘s the docs:

As I said, I also used the full ARN (copied from AWS panel) but it's ok, I'd prefer to not call it from another lambda, if possible.

> Regarding esbuild settings, I have a sample project that uses the following

I think putting it in `custom` is better, than at the top of the config, otherwise I get this error:

```
Warning: Invalid configuration encountered
  at root: unrecognized property 'esbuild'
```

I tried `exclude` (as you did, instead of `external`, as in docs) like this:

```yml
custom:
  esbuild:
  bundle: true
  minify: false
  exclude:
    - duckdb
```

results in this:

```
undefined	ERROR	Uncaught Exception 	{"errorType":"Error","errorMessage":"/var/task/src/package.jsondoes not exist","stack":["Error: /var/task/src/package.jsondoes not exist","    at exports2.find (/var/task/src/handlers/search.js:71990:15)","    at node_modules/duckdb/lib/duckdb-binding.js (/var/task/src/handlers/search.js:72269:31)","    at __require (/var/task/src/handlers/search.js:11:50)","    at node_modules/duckdb/lib/duckdb.js (/var/task/src/handlers/search.js:72278:18)","    at __require (/var/task/src/handlers/search.js:11:50)","    at Object.<anonymous> (/var/task/src/handlers/search.js:72560:29)","    at Module._compile (node:internal/modules/cjs/loader:1256:14)","    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)","    at Module.load (node:internal/modules/cjs/loader:1119:32)","    at Module._load (node:internal/modules/cjs/loader:960:12)"]
```

I am going to give up on esbuild here, install webpack + the 20 extra dev modules, and be ok with the slower build & more complex config. It seems to work.

**Comment by tobilg** [comment]
The below snippet has a wrong indentation, everything below `esbuild` needs to be 2 spaces to the right:

> ```yaml
> custom:
>   esbuild:
>   bundle: true
>   minify: false
>   exclude:
>     - duckdb
> ```

like this:

```yaml
custom:
  esbuild:
    bundle: true
    minify: false
    exclude:
      - duckdb
```
